AFP/AFP/Models/Cita.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace AFP.Models
{
    public class Cita
    {
        public int Id { get; set; }
        public DateTime FechaCita { get; set; }
        [Required(ErrorMessage = "El Descripcion es obligatorio")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El Paciente es obligatorio")]
        public string Paciente { get; set; }
        [Required(ErrorMessage = "El Doctor es obligatorio")]
        public string Doctor { get; set; }
    }
}

AFP/AFP/Controllers/CitaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AFP.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace AFP.Controllers
{
    public class CitaController : Controller
    {
        private readonly CitaContext context;
        public CitaController()
        {
            context = new CitaContext();
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View(context.GetAll().ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Cita ci)
        {
            if (ModelState.IsValid)
            {
                context.Add(ci);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [HttpGet]
        public IActionResult Detail(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var model = new Cita();
            var lsprod = context.GetAll().Where(x => x.Id == id);
            foreach (var p in lsprod)
            {
                model.FechaCita = p.FechaCita;
                model.Descripcion = p.Descripcion;
                model.Paciente = p.Paciente;
                model.Doctor = p.Doctor;

            }
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var model = new Cita();
            var lsprod = context.GetAll().Where(x => x.Id == id);
            foreach (var p in lsprod)
            {
                model.Id = p.Id;
                model.FechaCita = p.FechaCita;
                model.Descripcion = p.Descripcion;
                model.Paciente = p.Paciente;
                model.Doctor = p.Doctor;

            }
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(Cita ci)
        {
            if (ModelState.IsValid)
            {
                context.Update(ci);
                return RedirectToAction(nameof(Index));
            }
            return View(ci);
        }
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = new Cita();
            var lsprod = context.GetAll().Where(x => x.Id == id);
            foreach (var p in lsprod)
            {
                model.Id = p.Id;
                model.FechaCita = p.FechaCita;
                model.Descripcion = p.Descripcion;
                model.Doctor = p.Doctor;
                model.Paciente = p.Paciente;

            }
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult DeleteRegitro(Cita cita)
        {
            context.Delete(cita.Id);
            return RedirectToAction(nameof(Index));

        }
    }
}

AFP/AFP/Views/Cita/Create.cshtml
@model AFP.Models.Cita

@{ ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1>Crear</h1>

<h4>Cita</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaCita" class="control-label">Fecha Cita</label>
                <input asp-for="FechaCita" class="form-control" />
                <span asp-validation-for="FechaCita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripcion</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paciente" class="control-label">Paciente</label>
                <input asp-for="Paciente" class="form-control" />
                <span asp-validation-for="Paciente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Doctor" class="control-label">Doctor</label>
                <input asp-for="Doctor" class="form-control" />
                <span asp-validation-for="Doctor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" class="btn btn-success"><i class="fas fa-user"></i> Crear Cita</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

AFP/AFP/Views/Cita/Delete.cshtml
@model AFP.Models.Cita

@{ ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1>ELiminar Cita</h1>
<h3>¿Esta seguro de eliminar la siguiente cita?</h3>
<br />
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCita)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaCita)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Paciente)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Paciente)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Doctor)
        </dd>
    </dl>

    <form asp-action="DeleteRegitro">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar</a>
    </form>
</div>

AFP/AFP/Views/Cita/Detail.cshtml
@model AFP.Models.Cita

@{ ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1>Detalle</h1>

<h4>Cita</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaCita" class="control-label">Fecha Cita</label>
                <input asp-for="FechaCita" class="form-control" readonly />
                <span asp-validation-for="FechaCita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripcion</label>
                <input asp-for="Descripcion" class="form-control" readonly />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paciente" class="control-label">Paciente</label>
                <input asp-for="Paciente" class="form-control" readonly />
                <span asp-validation-for="Paciente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Doctor" class="control-label">Doctor</label>
                <input asp-for="Doctor" class="form-control" readonly />
                <span asp-validation-for="Doctor" class="text-danger"></span>
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

AFP/AFP/Views/Cita/Edit.cshtml
@model AFP.Models.Cita

@{ ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1>Editar</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FechaCita" class="control-label">Fecha Cita</label>
                <input asp-for="FechaCita" class="form-control" />
                <span asp-validation-for="FechaCita" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label">Descripcion</label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Paciente" class="control-label">Paciente</label>
                <input asp-for="Paciente" class="form-control" />
                <span asp-validation-for="Paciente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Doctor" class="control-label">Doctor</label>
                <input asp-for="Doctor" class="form-control" />
                <span asp-validation-for="Doctor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Edit" class="btn btn-success"><i class="fas fa-user"></i> Guardar</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar</a>
</div>

AFP/AFP/Views/Cita/Index.cshtml
@model IEnumerable<AFP.Models.Cita>
@{
    ViewData["Title"] = "Product";
}

<h1 class="text-center">CRUD Cita</h1>
<div class="row">
    <div class="col-12">
        <div class="float-right">
            <a asp-action="Create" asp-controller="Cita" class="btn btn-success"><i class="fas fa-plus"></i> Nuevo Producto</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card border">
            <div class="card-header">
                <h3>
                    <strong>Lista de citas</strong>
                </h3>
                <div class="card body">
                    <div class="table-responsive">
                        @if (Model.Count() > 0)
                        {
                            <table class="table table-bordered" id="tablaCita" width="100%" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>@Html.DisplayNameFor(m => m.FechaCita)</th>
                                        <th>@Html.DisplayNameFor(m => m.Descripcion)</th>
                                        <th>@Html.DisplayNameFor(m => m.Paciente)</th>
                                        <th>@Html.DisplayNameFor(m => m.Doctor)</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td>@Html.DisplayFor(m => item.FechaCita)</td>
                                        <td>@Html.DisplayFor(m => item.Descripcion)</td>
                                        <td>@Html.DisplayFor(m => item.Paciente)</td>
                                        <td>@Html.DisplayFor(m => item.Doctor)</td>
                                        <td>
                                            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                                            <a class="btn btn-info" asp-action="Detail" asp-route-id="@item.Id">Detalle</a>
                                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>No hay registro</p>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>$(document).ready(() => {
    $('#tablaProducto').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "No hay información",
                    "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
                    "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
                    "infoFiltered": "(Filtrado de _MAX_ total entradas)",
                    "infoPostFix": "",
                    "thousands": ",",
                    "lengthMenu": "Mostrar _MENU_ Entradas",
                    "loadingRecords": "Cargando...",
                    "processing": "Procesando...",
                    "search": "Buscar:",
                    "zeroRecords": "Sin resultados encontrados",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    }
                }
            });
        })</script>
}